#!/usr/bin/env python3 -I
"""Generate src/guide.u from docs/guide/*.md (the guide embedded in the server). Run by build.sh."""
import os, re, sys

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
topics = ["unison-basics", "http-json", "mcp-client", "oauth", "cdp", "process-ffi", "traps"]


def camel(t):
    p = t.split("-")
    return p[0] + "".join(x.capitalize() for x in p[1:])


def lit(line):
    s = line.replace("\\", "\\\\").replace('"', '\\"').replace("\t", "\\t")
    for ch in s:
        if ord(ch) > 126 or (ord(ch) < 32):
            sys.exit(f"gen-guide: non-ASCII or control character in guide line: {line!r}")
    return '"' + s + '"'


out = ["-- GENERATED by scripts/gen-guide.py from docs/guide/*.md. Do not edit.", ""]
for t in topics:
    lines = open(os.path.join(root, "docs", "guide", t + ".md"), encoding="utf8").read().rstrip("\n").split("\n")
    out.append(f"Guide.text.{camel(t)} : Text")
    out.append(f"Guide.text.{camel(t)} = Text.join \"\\n\" [")
    out.append(",\n".join("  " + lit(l) for l in lines) + "]")
    out.append("")
out.append("Guide.topics : [(Text, Text)]")
out.append("Guide.topics = [" + ", ".join(f'("{t}", Guide.text.{camel(t)})' for t in topics) + "]")
new = "\n".join(out) + "\n"
path = os.path.join(root, "src", "guide.u")
if not os.path.exists(path) or open(path, encoding="utf8").read() != new:
    open(path, "w", encoding="utf8").write(new)
